### ISSUE TITLE
Workflow status shows failing while the action runs are green

### ISSUE THREAD

**Issue by yaxiong-zhao** [bazelbuild/setup-bazelisk#71] opened 2022-12-23 05:28 UTC
Not sure if this is the right place to file this issue
The issue is that the workflow constantly running green, but the workflow status badge always shows failing
See the screenshot below:

<img width="1019" alt="截屏2022-12-22 下午9 26 45" src="https://user-images.githubusercontent.com/112656580/209276549-c4ee28fc-e140-40c9-9f5b-cd6c7ca0ee9a.png">
<img width="247" alt="截屏2022-12-22 下午9 27 10" src="https://user-images.githubusercontent.com/112656580/209276592-f29d6623-be8f-4836-a8b6-4d251fff4961.png">

The full content of the yaml file:

```yaml
# https://github.com/bazelbuild/setup-bazelisk
name: build-and-test
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-and-test:
    name: bazel-build-and-test
    runs-on: ubuntu-latest
    container: gcr.io/some-repo/dev_image:202211211459
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //src/...
      - run: bazel test //src/...
```

**Comment by mishas** [comment] 2022-12-23 14:31
Hello @yaxiong-zhao ,

I think the problem is somewhere with how the badge is working, and is unrelated to the `setup-bazelisk` action.

I'm closing this issue.

It's possible, btw, that the badge URL you're using is incorrect (tracking the wrong branch or something), but that's just a guess, as I don't know what configuration you have for that badge (which URL is being used)

**Closed by mishas** 2022-12-23 14:31 UTC
